title: Willforsyth
name: Digital home for Will Forsyth
description: I am a UI / UX designer and developer with an emphasis on UX. An experience designer with strong Front End skills; Quickly prototype concepts to demonstrate and test ideas;
url: willforsyth.co.uk
author: Will Forsyth
markdown: kramdown
gems:
  - jekyll-seo-tag
twitter:
  username: willforsyth
kramdown:
  auto_ids: false
collections:
  components:
   output: true
  templates:
   output: true
