title: Willforsyth
name: Blog and play ground
description: I am a front end developer with an emphasis on UX. I love user research and finding the best solution for the user. Ensuring all code is accessible and modular.
url: willforsyth.co.uk
author: Will Forsyth
markdown: kramdown
gems:
  - jekyll-seo-tag
twitter:
  username: willforsyth
kramdown:
  auto_ids: false
collections:
  components:
   output: true
  templates:
   output: true
