title: Willforsyth
name: Blog and play ground
description: I am a UI / UX designer and developer with an emphasis on UX. I love user research and finding the best solution for the user. Ensuring all code and designers is accessible and modular. An experienced designer with strong Front End skills; Strong knowledge of HTML/CSS/JS, graceful degradation and progressive enhancement; Familiar with NPM, git, and build systems; Experience with React and Meteor;Code is neat, tested, readable and well documented; Large Experience with UX taking large sites from concept to hand over to designers ( Wireframes, sitemaps, IA, and research. ); Ability to work within multidisciplinary teams with visual designers, motion designers and developers; Quickly prototype concepts to demonstrate and test ideas; You’re resilient under pressure and thrive in a fast paced environment.
url: willforsyth.co.uk
author: Will Forsyth
markdown: kramdown
gems:
  - jekyll-seo-tag
twitter:
  username: willforsyth
kramdown:
  auto_ids: false
collections:
  components:
   output: true
  templates:
   output: true
